$ErrorActionPreference = 'Stop'
Set-Location (Split-Path $PSScriptRoot -Parent)
$nl = [string][char]13 + [string][char]10
$lines = New-Object System.Collections.Generic.List[string]
function A([string]$s){ [void]$lines.Add($s) }

A 'Unicode true'
A '!include "MUI2.nsh"'
A '!include "nsDialogs.nsh"'
A '!include "LogicLib.nsh"'
A ''
A 'Name "NoVoice"'
A 'OutFile "..\release\NoVoice-Setup.exe"'
A 'InstallDir "$LOCALAPPDATA\NoVoice"'
A 'RequestExecutionLevel user'
A 'SetCompressor /SOLID lzma'
A ''
A '!define MUI_ABORTWARNING'
A '!define MUI_ICON "..\src-tauri\icons\icon.ico"'
A '!define MUI_UNICON "..\src-tauri\icons\icon.ico"'
A '!define MUI_WELCOMEFINISHPAGE_BITMAP "installer-art\wizard-sidebar.bmp"'
A '!define MUI_UNWELCOMEFINISHPAGE_BITMAP "installer-art\wizard-sidebar.bmp"'
A '!define MUI_HEADERIMAGE'
A '!define MUI_HEADERIMAGE_BITMAP "installer-art\wizard-header.bmp"'
A '!define MUI_HEADERIMAGE_RIGHT'
A ''
A '!define MUI_WELCOMEPAGE_TITLE "欢迎使用 NoVoice"'
A '!define MUI_WELCOMEPAGE_TEXT "NoVoice 用于去掉视频里的人声，画面保持无损。$\r$\n$\r$\n点击「下一步」继续安装。"'
A '!define MUI_FINISHPAGE_TITLE "安装完成"'
A '!define MUI_FINISHPAGE_TEXT " "'
A '!define MUI_FINISHPAGE_RUN "$INSTDIR\launch-novoice.vbs"'
A '!define MUI_FINISHPAGE_RUN_TEXT "立即启动 NoVoice"'
A '!define MUI_FINISHPAGE_RUN_FUNCTION LaunchNoVoice'
A '!define MUI_FINISHPAGE_SHOWREADME'
A '!define MUI_FINISHPAGE_SHOWREADME_TEXT "在桌面添加快捷方式"'
A '!define MUI_FINISHPAGE_SHOWREADME_FUNCTION CreateDesktopShortcut'
A ''
A '!insertmacro MUI_PAGE_WELCOME'
A '!insertmacro MUI_PAGE_DIRECTORY'
A '!insertmacro MUI_PAGE_INSTFILES'
A '!insertmacro MUI_PAGE_FINISH'
A '!insertmacro MUI_UNPAGE_CONFIRM'
A '!insertmacro MUI_UNPAGE_INSTFILES'
A '!insertmacro MUI_LANGUAGE "SimpChinese"'
A ''
A 'Function CreateDesktopShortcut'
A '  CreateShortCut "$DESKTOP\NoVoice.lnk" "$INSTDIR\launch-novoice.vbs" "" "$INSTDIR\NoVoice.exe"'
A 'FunctionEnd'
A ''
A 'Function LaunchNoVoice'
A '  SetOutPath "$INSTDIR"'
A '  ExecShell "open" "$INSTDIR\launch-novoice.vbs"'
A 'FunctionEnd'
A ''
A 'Section "Install"'
A '  SetOutPath "$INSTDIR"'
A '  File "/oname=NoVoice.exe" "..\release\NoVoice\NoVoice.exe"'
A '  File "/oname=bootstrap-and-run.bat" "..\scripts\bootstrap-and-run.bat"'
A '  File "/oname=launch-novoice.vbs" "..\scripts\launch-novoice.vbs"'
A '  File "/oname=first_run_setup_gui.py" "..\scripts\first_run_setup_gui.py"'
A '  File "/oname=requirements.txt" "..\requirements.txt"'
A '  CreateDirectory "$INSTDIR\models"'
A '  File "/oname=models\README.md" "..\models\README.md"'
A '  CreateDirectory "$SMPROGRAMS\NoVoice"'
A '  CreateShortCut "$SMPROGRAMS\NoVoice\NoVoice.lnk" "$INSTDIR\launch-novoice.vbs" "" "$INSTDIR\NoVoice.exe"'
A '  CreateShortCut "$SMPROGRAMS\NoVoice\卸载 NoVoice.lnk" "$INSTDIR\Uninstall.exe"'
A '  WriteUninstaller "$INSTDIR\Uninstall.exe"'
A ''
A '  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "DisplayName" "NoVoice 视频去人声"'
A '  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "DisplayIcon" "$INSTDIR\NoVoice.exe"'
A '  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "Publisher" "cat7street"'
A '  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "DisplayVersion" "0.1.0"'
A '  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "InstallLocation" "$INSTDIR"'
A '  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""'
A '  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "QuietUninstallString" "$\"$INSTDIR\Uninstall.exe$\" /S"'
A '  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "NoModify" 1'
A '  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice" "NoRepair" 1'
A 'SectionEnd'
A ''
A 'Section "Uninstall"'
A '  Delete "$SMPROGRAMS\NoVoice\NoVoice.lnk"'
A '  Delete "$SMPROGRAMS\NoVoice\卸载 NoVoice.lnk"'
A '  RMDir "$SMPROGRAMS\NoVoice"'
A '  Delete "$DESKTOP\NoVoice.lnk"'
A '  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\NoVoice"'
A '  RMDir /r "$INSTDIR"'
A 'SectionEnd'

$nsi = ($lines -join $nl) + $nl
$utf16 = New-Object System.Text.UnicodeEncoding $false, $true
$path = Join-Path (Get-Location) 'scripts\NoVoice-Setup.nsi'
[IO.File]::WriteAllText($path, $nsi, $utf16)

$makensis = 'C:\Users\52352\AppData\Local\tauri\NSIS\makensis.exe'
Push-Location scripts
& $makensis 'NoVoice-Setup.nsi'
$code = $LASTEXITCODE
Pop-Location
Write-Output ('exit=' + $code)
if ($code -eq 0) { Get-Item 'release\NoVoice-Setup.exe' | Format-List Name,Length,LastWriteTime }
else { Write-Output 'BUILD_FAILED' }